=== uzair-waseem/xml/index.dtd
<!ELEMENT companies (A:company, B:company, C:company, D:company )>
<!ELEMENT A:company (A:employeenum , A:employname , A:adress , A:salery )>
<!ELEMENT B:company (B:employeenum , B:employname , B:adress , B:salery )>
<!ELEMENT C:company (C:employeenum , C:employname , C:adress , C:salery )>
<!ELEMENT D:company (D:employeenum , D:employname , D:adress , D:salery )>
<!ELEMENT A:employeenum (#PCDATA)>
<!ELEMENT A:employname (#PCDATA)>
<!ELEMENT A:adress (#PCDATA)>
<!ELEMENT A:salery (#PCDATA)>
<!ELEMENT B:employeenum (#PCDATA)>
<!ELEMENT B:employname (#PCDATA)>
<!ELEMENT B:adress (#PCDATA)>
<!ELEMENT B:salery (#PCDATA)>
<!ELEMENT C:employeenum (#PCDATA)>
<!ELEMENT C:employname (#PCDATA)>
<!ELEMENT C:adress (#PCDATA)>
<!ELEMENT C:salery (#PCDATA)>
<!ELEMENT D:employeenum (#PCDATA)>
<!ELEMENT D:employname (#PCDATA)>
<!ELEMENT D:adress (#PCDATA)>
<!ELEMENT D:salery (#PCDATA)>

<!ATTLIST companies xmlns:A CDATA #REQUIRED>
<!ATTLIST companies xmlns:B CDATA #REQUIRED>
<!ATTLIST companies xmlns:C CDATA #REQUIRED>
<!ATTLIST companies xmlns:D CDATA #REQUIRED>

=== uzair-waseem/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Prolog -->

<!DOCTYPE companies SYSTEM "index.dtd" [

]>





<companies xmlns:A= "https://www.gmail.com" xmlns:B= "https://www.yahoo.com" xmlns:C= "https://www.gmail.com" xmlns:D= "https://www.yahoo.com">
    <A:company>
        <A:employeenum>03113228995 </A:employeenum>
        <A:employname>Uzair</A:employname>
        <A:adress> orangi town 10 no </A:adress>
        <A:salery>15000 </A:salery>
    </A:company>




    <B:company>
        <B:employeenum>03113228995 </B:employeenum>
        <B:employname>Huzaifa</B:employname>
        <B:adress> orangi town 20 no </B:adress>
        <B:salery>2000 </B:salery>
    </B:company>




    <C:company>
        <C:employeenum>03113228995 </C:employeenum>
        <C:employname>Rafay</C:employname>
        <C:adress> orangi town 50 no </C:adress>
        <C:salery>1000 </C:salery>
    </C:company>


    <D:company>
        <D:employeenum>03113228995 </D:employeenum>
        <D:employname>Uzair hashmi</D:employname>
        <D:adress> gujrat </D:adress>
        <D:salery>5000 </D:salery>
    </D:company>
</companies>
